parameters:
#    syrup_core.example.class: Syrup\CoreBundle\Example

services:
    syrup_core.routing_loader:
        class: Syrup\CoreBundle\Routing\Loader
        arguments: [%components%]
        tags:
            - { name: routing.loader }
